### ISSUE TITLE
Plans for supporting Mapnik 2

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2198]
Currently this style works both in Mapnik 2 and Mapnik 3.

But some rules that are available in Mapnik 3 are not present in Mapnik 2. Using them would cause Mapnik 2 renderers to fail.

How long we want to support Mapnik 2? Most likely at least untill https://github.com/openstreetmap/chef/issues/39 is completed.

Note that stopping to support Mapnik 2 means that using current TileMill version to render the style will be impossible. Given that TileMill is officially abandoned by Mapbox it would require to either drop TileMill support or to fork TileMill to release a new version.

Kosmtik would continue to work fine.

At least some rules were renamed - for example to achieve on points/areas effect of `text-min-distance` in 2.3 it is necessary to use `text-margin` in 3.0. As result it is impossible to support 2.3, 3.0 and use `text-min-distance`/`text-margin` effect at once.

**Comment by gravitystorm** [comment]
If the stylesheets can't be used by tilemill then we decrease the pool of contributors and decrease the opportunities to reuse the styles. Tilemill is still the only CartoCSS design tool that has proper releases and windows support. Kosmtik is a source-only install and doesn't have any windows builds.

I'd love to see a mapnik 3 version of tilemill, but I don't know if that's likely to happen. Does anyone know if there are any forks or non-mapbox versions in development?

If we assume Tilemill isn't an option, what will we suggest to developers and end-users that they use instead? Kosmtik is fine if you don't mind command-line parameters and doing everything in separate text editors but it's a huge step back for those who enjoy various features of Tilemill.

**Comment by math1985** [comment]
> I'd love to see a mapnik 3 version of tilemill, but I don't know if that's likely to happen. Does anyone know if there are any forks or non-mapbox versions in development?

As far as I know, Tilemill has been supporting Mapnik 3 already since October 2014. See this change: https://github.com/mapbox/tilemill/commit/818826c3f32162dd4a337f9fcb1c8ca60d29ba1b

**Comment by matkoniecz** [comment]
> doing everything in separate text editors

I wanted to note that it is anyway necessary with mapnik - but from what I see it is also fixed in an unreleased tilemill (https://github.com/mapbox/tilemill/issues/190)

> tagging a new release and perhaps compiling binaries.

And making ppa with packages. There is no tilemill package for Ubuntu 16 - and MapBox is not going to make one. So it makes TileMill source-only install.

**Comment by SomeoneElseOSM** [comment]
Speaking as a TileMill user...

Re TileMill vs Kosmtik, the documentation at https://github.com/kosmtik/kosmtik seems to have improved considerably since I last looked at it but it still isn't where the "TileMill Crash Course" is.  It's that, rather than any reliance on an external editor (which you tend to have to use in TileMill anyway with any reasonable number of layers) or command line options (likely needed anyway for file extract processing) which is what will be most missed, but that I guess is "simply a matter of documentation" :)

Re TileMill and Ubuntu 16; support for 14.04 LTS is good until 2019 or so, so it's not too immediate an issue.  Windows support might be to some people (although I never could get TileMill on Windows working with a remote database on Linux, so it's not an issue for me).

**Comment by nebulon42** [comment]
I think with a bit of effort it is possible to e.g. bring Kosmtik to npm and therefore decrease the effort when installing and using it. Also I think having regular releases is more a matter of policy than of anything missing in the software.
cc @yohanboniface

**Comment by mboeringa** [comment]
> Tilemill is still the only CartoCSS design tool that has proper releases and windows support. Kosmtik is a source-only install and doesn't have any windows builds.

> Windows support might be to some people (although I never could get TileMill on Windows working with a remote database on Linux, so it's not an issue for me).

Is the new **Windows Subsystem for Linux** that Microsoft unveiled, of any relevance here?:

http://www.theverge.com/2016/3/30/11331014/microsoft-windows-linux-ubuntu-bash

https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/

**Comment by jojo4u** [comment]
Tilemill has been pulled from Github: https://github.com/mapbox/tilemill/ is 404.
Perhaps a poll among the contributors who actually use Tilemill?

**Comment by kocio-pl** [comment]
No worry, it was just moved out of the Mapbox profile:

https://www.mapbox.com/blog/fall-cleaning/
https://github.com/tilemill-project/tilemill

**Comment by kocio-pl** [comment]
Superseded by more general https://github.com/gravitystorm/openstreetmap-carto/issues/2458.
