### ISSUE TITLE
land has same background as water

### ISSUE THREAD

**Issue by brunesto** [gravitystorm/openstreetmap-carto#3791]
This is happening on openstreetmap.org, but I dont know how to report it

https://c.tile.openstreetmap.org/9/247/201.png
![image](https://user-images.githubusercontent.com/2085291/58486721-af58f200-8166-11e9-89fa-ffb0e3aee7e0.png)

The same happens in Spain and Saudi arabia... I guess it is a consequence of global warming ;)

**Comment by matkoniecz** [comment]
It is almost certainly data issue and should be gone now or in the near future, not caused by a bug in the map style.

Try to refresh cache - almost certainly data and rendering is now fixed.

In unlikely case that it persists - please comment.

**Comment by brunesto** [comment]
It is still happening, but not systematically:

$ for i in `seq 1  10`; do wget https://a.tile.openstreetmap.org/9/247/201.png; done

$ md5sum 201.png*
e9ff649247d76499ecc6d9234ab92ff7  201.png
a98d4b11842a1108c90cfa2e56b80ae5  201.png.1
e9ff649247d76499ecc6d9234ab92ff7  201.png.2
7e4e16062f4aafe39ebe113733534b97  201.png.3
a98d4b11842a1108c90cfa2e56b80ae5  201.png.4
a98d4b11842a1108c90cfa2e56b80ae5  201.png.5
a98d4b11842a1108c90cfa2e56b80ae5  201.png.6
a98d4b11842a1108c90cfa2e56b80ae5  201.png.7
a98d4b11842a1108c90cfa2e56b80ae5  201.png.8
a98d4b11842a1108c90cfa2e56b80ae5  201.png.9


a98d4b11842a1108c90cfa2e56b80ae5 are the ones with blue background color for land

**Comment by Nakaner** [comment]
I found the reason for the Arabian peninsula becoming blue. It was caused by a editing mistake. Changeset 70664569 changed the Arabia Peninsula (relation 5631846) from `place=peninsula` to `natural=water`. Because the of Strait of Hormuz was changed from `natural=strait` to `natural=water` in the same changeset, I decided to [revert](https://www.openstreetmap.org/changeset/70664569) the whole changeset.

How did I find it? I searched OSMCha for changesets between 27 and 28 May 2019 which have been flagged by any validation rule. Changes to large waterbodies are catched by at least one rule. I limited the number of results by adding a bbox filter around the Arabian Peninsula. The changeset in question was the 8th item in the list of results.

**Comment by jeisenbe** [comment]
Thank you for fixing those errors

**Comment by brunesto** [comment]
I see the same issue in south of Spain:
https://a.tile.openstreetmap.org/9/251/199.png 

(again it does not pop up in blue everytime, maybe 50%)

![](https://a.tile.openstreetmap.org/9/251/199.png)

After reading comment from Nakaner I checked the iberian peninsula  https://www.openstreetmap.org/relation/3870917 but it has does not have any tag with value 'water' ... So i don't know what is causing the problem there (or if it has already been fixed I am just seeing some old tiles)

**Comment by matkoniecz** [comment]
> old tiles

Have you tried clearing browser cache?

https://www.openstreetmap.org/#map=8/36.847/-4.098 for me is without flood

**Comment by brunesto** [comment]
I used wget to directly query the tile and avoid browser cache. 
Now if I use the browser I see some tiles with water on zoom level 9 (but not 8)
https://www.openstreetmap.org/#map=9/36.8470/-4.0980

**Comment by Adamant36** [comment]
@matkoniecz, it seems to be happening [here](https://www.openstreetmap.org/#map=18/40.08371/-122.52390) on Z18 also. It doesn't look like there's any data around the borders of it either like it was mapped by someone. I'm the only one that really edits that area. Are you sure its not something caused by the last Carto release? Like maybe bleed out from a pond around there or something? I thought @jeisenbe did something related to water bodies in the last release. 

If it's not a bug and it's a vandal could you look into it and have them blocked? Because I'm not seeing any edits around there besides mine. Unless I'm missing something.

**Comment by Adamant36** [comment]
@matkoniecz, it still seems to be going on at the place I linked to.

**Comment by brunesto** [comment]
Now the tiles for Tangier https://c.tile.openstreetmap.org/9/247/201.png are displayed correctly.

@Adamant36 , I just tried against one tile  in the area you mentioned. The tiles returned were always of the correct land background color, so probably you are seeing old tiles cached by your browser.

bash script to retrieve 10 times a tile against a,b,and c tiles server:
```
for x in a b c; do mkdir $x; cd $x; for i in `seq 1 10`; do wget https://$x.tile.openstreetmap.org/18/41857/99161.png ; done ; cd .. ; done
```

**Comment by Adamant36** [comment]
> so probably you are seeing old tiles cached by your browser.

I doubt it would be cached still 7 days later. I've restarted my computer a bunch of times between then.

**Comment by Adamant36** [comment]
@brunesto, can you check here https://www.openstreetmap.org/#map=18/40.08416/-122.51376

**Comment by brunesto** [comment]
@Adamant36, on the browser it looks fine for me, I also ran the bash script against tile
[18/41859/99161](https://c.tile.openstreetmap.org/18/41859/99161.png) 

![image](https://user-images.githubusercontent.com/2085291/59016844-7f82ac00-8842-11e9-9412-ac392ceccb86.png)

For me the tile returned is always with correct land background

**Comment by HolgerJeromin** [comment]
> I doubt it would be cached still 7 days later. I've restarted my computer a bunch of times between then.

There are many places where caching can be. Please try another browser or even another computer.

**Comment by kocio-pl** [comment]
Another problem was visible lately, here is some explanation what might be the reason if that happens:

https://lists.openstreetmap.org/pipermail/talk-au/2019-June/012719.html

**Comment by Adamant36** [comment]
Thanks for the link. I had seen it happen a few times again and I was totally thinking there was probably more to it then just caching.
