### ISSUE TITLE
Possible to use unhinted Noto Arabic?

### ISSUE THREAD

**Issue by mapmeld** [gravitystorm/openstreetmap-carto#4152]
### Expected behavior

In Qalat Street (Erbil/Hawler, Iraqi Kurdistan) the ligature ڵا is not rendered correctly in the current Noto Arabic font. It's an open issue since 2018 or earlier: https://github.com/googlefonts/noto-fonts/issues/1098 - if I remember right, this and other ligatures are used a few other places in Iraq and Iran

### Actual behavior

On the map: https://www.openstreetmap.org/#map=19/36.19151/44.00536 it appears as two separate characters in a U shape

![Screen Shot 2020-05-30 at 5 02 16 AM](https://user-images.githubusercontent.com/643918/83324369-d1ca9300-a232-11ea-8167-5b3651055b1f.png)

On the original GitHub issue, today someone claimed that Noto Sans Arabic unhinted doesn't have this problem. Can we use this?

**Comment by kmuncie** [comment]
You may want to take a look at https://github.com/googlefonts/noto-fonts/issues/1555#issuecomment-635592028 - the latest version of Noto Sans Arabic v2.500 seems to be undergoing a large redesign according to the metadata and my testing showed a large number of regressions in its current state.

**Comment by mapmeld** [comment]
Looks like this was just fixed in Noto? But unclear to me when this change will be generally available and when OSM would update their font https://github.com/googlefonts/noto-source/pull/270

**Comment by nizarsq** [comment]
This issue fixed in NotoSansArabic.

**Comment by pnorman** [comment]
Closing as this appears to be fixed upstream. We already have [guidance on having an up-to-date version of Noto](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#non-latin-scripts) for non-latin scripts.

**Comment by mapmeld** [comment]
I still see the issue with this character on OSM ( tile: https://tile.openstreetmap.org/19/326236/205532.png )
A new version of Noto Arabic was just released resolving this. Could it be used in future carto tile renders?
https://github.com/notofonts/arabic/releases

**Comment by imagico** [comment]
There are essentially three possibilities here:

1. the claim that the problem is fixed in the Noto font we use for Arabic is wrong.
2. we screwed up the font management and end up not using the latest version of Noto for Arabic.
3. OSMF operations did not correctly deploy the style.

Which of these applies is easy enough to figure out:  Someone needs to set up the style according to [our instructions](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md) and check if the problem as observed still exists.  Please note that there are some differences in font handling between node-mapnik (used by kosmtik) and other mapnik bindings - see https://github.com/mapnik/node-mapnik/blob/master/lib/mapnik.js.  This can lead to differences between development environments and operational deployments.

If evaluation reveals that 2. is the case please open a new issue presenting the evidence.

**Comment by imagico** [comment]
According to https://github.com/openstreetmap/operations/issues/976 it could be that the reason is the fonts on the OSMF servers have not been updated since the last style release.
